# ---------------------------------------------------
# MongoDB Headless Service
# ---------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  clusterIP: None  # headless service
  selector:
    app: mongodb
    tier: db
    project: roboshop
  ports:
    - name: mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017

---
# ---------------------------------------------------
# MongoDB StatefulSet
# ---------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  serviceName: "mongodb"
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: joindevops/mongodb
          ports:
            - containerPort: 27017
              name: mongodb-port
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp3"  # specify your storage class name
        resources:
          requests:
            storage: 1Gi
...