# ---------------------------------------------------
# StorageClass for MySQL
# ---------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-dynamic-ebs-mysql
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
---
# ---------------------------------------------------
# MySQL Headless Service
# ---------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  clusterIP: None    # headless service for stable DNS
  selector:
    app: mysql
    tier: db
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
# ---------------------------------------------------
# MySQL StatefulSet
# ---------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:1.2.0
        ports:
        - containerPort: 3306
          name: mysql-port
        envFrom:
        - configMapRef:
            name: mysql-config
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs-mysql"
      resources:
        requests:
          storage: 5Gi
---
# ---------------------------------------------------
# MySQL ConfigMap
# ---------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"
