apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    tier: db
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # this port belongs to service
    targetPort: 3306 # this port belongs to container
---
apiVersion: apps/v1 
kind: StatefulSet 
metadata:
  name: mysql
  namespace: roboshop 
  labels:    # # these labels belong to deployment
    app: mysql
    tier: db
    project: roboshop
spec:
  clusterIP: None
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
      tier: db
      project: roboshop
  serviceName: "mysql"
  replicas: 1 # by default is 1 
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
        tier: db
        project: roboshop       
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:1.2.0
        ports:
        - containerPort: 3306
          name: mysql-port
        envFrom:
        - configMapRef:
            name: mysql-config
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
  
...    
  

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # keep true in double quotes
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"