apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  clusterIP: None
  selector:
    app: redis
    tier: db  
    project: roboshop
  ports:  
  - name: redis-port
    protocol: TCP
    port: 6379 # this port belongs to service
    targetPort: 6379   # this port belongs to  container
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop 
  labels:    # # these labels belong to deployment
    app: redis
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app:  redis # has to match .spec.template.metadata.labels
      tier: db
      project: roboshop
  serviceName: "redis"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: redis # has to match .spec.selector.matchLabels
        tier: db
        project: roboshop
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"  # specify your storage class name
      resources:
        requests:
          storage: 1Gi
