# ---------------------------------------------------
# StorageClass for Roboshop (EBS CSI Driver)
# ---------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-dynamic-ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
---
# ---------------------------------------------------
# Redis Headless Service
# ---------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  clusterIP: None
  selector:
    app: redis
    tier: db  
    project: roboshop
  ports:  
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
---
# ---------------------------------------------------
# Redis StatefulSet
# ---------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop 
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db
      project: roboshop
  serviceName: "redis"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 1Gi
...